
import java.awt.Color;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jdevia
 */
public class AFRApp extends javax.swing.JFrame {

    private Automata automata;
    
    /**
     * Creates new form AFRApp
     */
    public AFRApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfcSeleccionadorArch = new javax.swing.JFileChooser();
        pnlSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtArchivoConfig = new javax.swing.JTextField();
        btnSeleccionArch = new javax.swing.JToggleButton();
        btnGenerar = new javax.swing.JButton();
        pnlInferior = new javax.swing.JPanel();
        lblResultado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        btnValidar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos XML","xml");
        jfcSeleccionadorArch.setFileFilter(filtro);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Autómata Finito Reconocedor");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(610, 400));
        setPreferredSize(new java.awt.Dimension(610, 420));
        setSize(new java.awt.Dimension(610, 420));

        pnlSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlSuperior.setPreferredSize(new java.awt.Dimension(608, 100));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Archivo Config.:");

        txtArchivoConfig.setMargin(new java.awt.Insets(2, 0, 2, 0));
        txtArchivoConfig.setPreferredSize(new java.awt.Dimension(80, 26));

        btnSeleccionArch.setText("...");
        btnSeleccionArch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionArchActionPerformed(evt);
            }
        });

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSuperiorLayout = new javax.swing.GroupLayout(pnlSuperior);
        pnlSuperior.setLayout(pnlSuperiorLayout);
        pnlSuperiorLayout.setHorizontalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArchivoConfig, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccionArch))
                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pnlSuperiorLayout.setVerticalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArchivoConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionArch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerar)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pnlSuperiorLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSeleccionArch, jLabel1, txtArchivoConfig});

        getContentPane().add(pnlSuperior, java.awt.BorderLayout.PAGE_START);

        pnlInferior.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlInferior.setPreferredSize(new java.awt.Dimension(608, 318));

        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Input:");

        txtInput.setMinimumSize(new java.awt.Dimension(14, 25));
        txtInput.setPreferredSize(new java.awt.Dimension(80, 28));

        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 2, 12))); // NOI18N
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(32767, 218));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(236, 218));

        txtLog.setColumns(20);
        txtLog.setLineWrap(true);
        txtLog.setTabSize(4);
        txtLog.setMaximumSize(new java.awt.Dimension(0, 0));
        txtLog.setMinimumSize(new java.awt.Dimension(0, 0));
        jScrollPane1.setViewportView(txtLog);

        javax.swing.GroupLayout pnlInferiorLayout = new javax.swing.GroupLayout(pnlInferior);
        pnlInferior.setLayout(pnlInferiorLayout);
        pnlInferiorLayout.setHorizontalGroup(
            pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInferiorLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlInferiorLayout.createSequentialGroup()
                        .addGroup(pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlInferiorLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtInput, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnValidar)
                                .addGap(5, 5, 5)))
                        .addGap(10, 10, 10))))
        );
        pnlInferiorLayout.setVerticalGroup(
            pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnValidar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlInferiorLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnValidar, jLabel3, txtInput});

        getContentPane().add(pnlInferior, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionArchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionArchActionPerformed
        int valorOpcion = this.jfcSeleccionadorArch.showOpenDialog(this);
        if (valorOpcion == 0) {
            txtArchivoConfig.setText(this.jfcSeleccionadorArch.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnSeleccionArchActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        try {
            if (automata != null) {
                Resultado resultado = automata.ejecutar(this.txtInput.getText());
                if (resultado.isAceptada()) {
                    lblResultado.setForeground(new Color(0, 160, 0));
                    lblResultado.setText("Cadena aceptada!!");
                } else {
                    lblResultado.setForeground(Color.red);
                    lblResultado.setText("Cadena rechazada!!");
                }
                txtLog.setForeground(Color.black);
                txtLog.setText(new String(resultado.getLog()));
            } else {
                lblResultado.setForeground(Color.red);
                lblResultado.setText("Aut\u00f3mata sin generar.");
                txtLog.setForeground(Color.red);
                txtLog.setText("Debe generar un aut\u00f3mata antes de validar la entrada!!");
            }
        }
        catch (Exception exc) {
            lblResultado.setForeground(Color.red);
            lblResultado.setText("Error al validar la cadena de entrada!!");
            txtLog.setForeground(Color.red);
            txtLog.setText((exc.getMessage()==null)?exc.getCause().getMessage():exc.getMessage());
            exc.printStackTrace();
        }
    }//GEN-LAST:event_btnValidarActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        try {
            String mensaje = null;
            lblResultado.setForeground(new Color(0, 160, 0));
            mensaje = (automata == null)?"Aut\u00f3mata generado.":"Se ha generado un nuevo Aut\u00f3mata.";
            automata = new Automata(this.txtArchivoConfig.getText());
            lblResultado.setText(mensaje);
        }
        catch (Exception exc) {
            lblResultado.setForeground(Color.red);
            lblResultado.setText("Fall\u00f3 la generaci\u00f3n del aut\u00f3mata!!");
            txtLog.setForeground(Color.red);
            txtLog.setText((exc.getMessage()==null)?exc.getCause().getMessage():exc.getMessage());
            exc.printStackTrace();
        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AFRApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AFRApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AFRApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AFRApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AFRApp app = new AFRApp();
                app.setLocationRelativeTo(null);
                app.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JToggleButton btnSeleccionArch;
    private javax.swing.JButton btnValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFileChooser jfcSeleccionadorArch;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JPanel pnlInferior;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JTextField txtArchivoConfig;
    private javax.swing.JTextField txtInput;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables

}
